const About = () => {
  return (
    <div className="about">
      <h1>About me</h1>
      <p>I go by tokisuno online, and I am a content creator from Ontario, Canada. I am 23 years old, graduated with my BA in Linguistics, and am now self-learning web-development while I am unable to work! I make videos on whatever I find interesting, whether it be language learning or a new keyboard I got interested in. I have a lot of interests...</p>
      <h2>Interests</h2>
      <h3>Linguistics/Languages</h3>
      <p>I first got into language learning around the time I was in Grade 7-8, when someone I knew was planning on moving to Spain and was learning Spanish in preparation of that. I thought that was really intersting, but I felt a deep dread inside me because I was a Latino who couldn't speak any Spanish. He was using this "hip and cool" website called Duolingo and I decided to give it a try some months later. From there started an addiction, my addiction to knowing about language. For the next 5 years I either did one of three things in my classes. 1) I would watch a lot of YouTube (with one of my all-time favourites being Ludwig and Slime's Melee commentary highlights), 2) I would try to learn programming outside of class, and 3) I would spend copious amounts of time trying to learn about language learning and finding the "right language for me". I remember spending hours every single day trying to find the cheat-code to learning languages, and to find the easiest language for me to learn. It's funny because looking back at it, it's very cringe. I had came to the same conclusion almost daily, which ultimately had me wasting a lot of time doing anything BUT learning my target languages.</p>
      <p>I didn't want to go to University, but my parents told me I had to apply and go because "it was the right thing to do". So I applied to a few places for Computer Science/Programming adjacent programs, and then McMaster University for Linguistics as a joke. My dad's closest friend is a professor there, so I thought it would be funny. Turns out I spent over 4 years there LOL. Linguistics is fascinating, and the branch I found the most interesting was the formal side. This includes fields like Syntax, Semantics, and Morphology. I was sooo deep in the sauce that I thought I was going to be a Syntactician when I was older. I wanted to pursue academia and figure out the secrets to language. I justified this in my brain by saying "I can still do programming with the knowledge I have", "I can still contribute to Computational Linguistics with this, right?", without actually knowing anything. I let myself stay in ignorance in fear of getting an answer I didn't like. So later after giving it some more thought, I decided to drop the idea of pursuing a Masters and spend more time programming. I've distanced myself quite a bit from Linguistics over the past several months due to me just needing a break, but I still really enjoy Linguistics. I am just trying to find my footing in what I find most interesting. I am interested in Historical Linguistics (arguably the most interesting field), Sociolinguistics, Pragmatics, Semantics, Conlangs, and Forensic Linguistics</p>
      <h3>Programming</h3>
      <p>I think I was about 6-8 years old when I first learned about scripting. I used to make VBA scripts to make fake pop-ups on windows, and I wrote some batch scripts to do things on windows. I remember I thought I was so impressive because in Grade 4, I was able to write a batch script that would open CMD on the school computers. This was huge because CMD was actually restricted on all the computers. I never really learned how to program until I was in Grade 9-10 when I discovered I could put Ubuntu on my Chromebook, and I had my first programming class. From there I was hooked, and would spend a lot of time learning about programming. Unfortunately, I didn't really know how to learn how to program, so I would only really learn in classes. I was a sitting duck without classes, and I would let my ego get the better of me whenever trying to start something new. I saw myself as "intermediate" despite only really making websites and learning some basic Python. After highschool, I just gave up programming entirely until I was in my second year. That's when I started playing around more with Python and C. I still wasn't a good programmer, but I was at least having some fun with it. Then during the summer of my final year of University, I discovered TheOdinProject, and I was HOOKED. Never before had I experienced such improvement since my first class in Grade 10. This is where I am now. I want to become sufficient in Ruby on Rails, and make some sort of side-hustle making websites for people!</p>
      <h3>Super Smash Brothers Melee</h3>
      <p>This game has been there for me in all points of my life, and I am grateful for having it. I wouldn't be the person I am today if it wasn't for the happy accident created back on November 21, 2001. For the first few years of me playing Melee, I was terrible. I mean, horrendous. I was the worst of my group of friends, I had very low self confidence, and an ego to push me further into the ground. Even before Melee, I was a terrible rager. I had problems regulating my emotions, and still do to this day (albiet I am not breaking controllers, shrieking at the top of my lungs, or smashing keyboards). I was very toxic, and thought there was a "right way" to play the game -- that is, I thought that I knew the only way to play the game. I have trouble understanding peoples' emotions and perspectives if I haven't been in them myself. Now I can recognise however just how wrong and close-minded I was. As it is with most autistic people, I have a strong sense of justice and what is right, and that too prevented me from really playing at all. Combine that with my undiagnosed ADHD and OCD at the time, and you have a recipe for disaster. It was also really hard to play people in-person because I had no way of going to tournaments, and the online play at the time was TERRIBLE. So once my friends grew tired of the game (and probably of me raging), I quit with them. I would play sometimes online, and I would sometimes practice tech skill to wear myself down before going to sleep, but I largely quit playing. This would have been around 2018</p>
      <p>Then the pandemic hit, and oh boy was that ever a time. I think the best thing the pandemic did for me was bring me Slippi, the best way to play Melee online. I was skeptical at first, because I was scarred by how bad Anthers with FasterMelee frame-buffering was. Once I saw Leffen praising it however, I was like "Okay, Leffen literally complains about everyting. This has to be good". It was that good. I was still very bad at first, but over time I started learning more about myself and how I want to play the game. I read books like "The Inner Game of Tennis", "Atomic Habits", and "Deep Work" which ultimately gave me a really good starting ground for improvement. I am still not a very good player by any means, but this game helped me through some very dark times in my life, and fundamentally changed who I am as a person. I have removed a lot of outside dependencies in order to be able to focus on things I find important, and I make time for those things that are important. This may have never happened had I not found Melee. Special shoutouts to Hamilton SSBM for hosting Hamilton Highgrounds, and the Toronto Melee scene. I love you guys.</p>
    </div>
  )
}

export default About;

